---
# aqua - Declarative CLI Version Manager
# https://aquaproj.github.io/
# checksum:
#   enabled: true
#   require_checksum: true
#   supported_envs:
#   - all
registries:
- type: standard
  ref: v4.4.0 # renovate: depName=aquaproj/aqua-registry
packages:
- name: cli/cli@v2.29.0
- name: peco/peco@v0.5.11
- name: rossmacarthur/sheldon@0.7.1
- name: starship/starship@v1.14.2
- name: direnv/direnv@v2.32.2
