- name: Include vars for MacOS
  include_vars: mac.yml
  when: ansible_facts['os_family'] == "Darwin"

- name: Include vars for Ubuntu
  include_vars: ubuntu.yml
  when: ansible_facts['os_family'] == "Debian"
  

- name: Make local bin directory
  file:
    path: "{{ cli.install_dir }}"
    state: directory

- name: Install
  shell: "{{ role_path }}/files/installer.sh {{ item.user }} {{ item.repo }} {{ cli.install_dir }}"
  args:
    creates: "{{ cli.install_dir }}/{{ item.repo }}"
  with_items: "{{ cli.golang }}"

- name: Import cargo
  import_tasks: cargo.yml