export ZDOTDIR=$HOME

export XDG_CONFIG_HOME=$HOME/.config

export LANG=ja_JP.UTF-8

export EDITOR=vim

export PATH=$HOME/.nodebrew/current/bin:$PATH
export PATH=$HOME/.local/bin:$PATH


export LD_LIBRARY_PATH=~/.cudnn/active/cuda/lib64:$LD_LIBRARY_PATH
export CPATH=~/.cudnn/active/cuda/include:$CPATH
export LIBRARY_PATH=~/.cudnn/active/cuda/lib64:$LIBRARY_PATH
