export ZDOTDIR=$HOME

export XDG_CONFIG_HOME=$HOME/.config

export LANG=ja_JP.UTF-8

export EDITOR=vim

export PATH=$HOME/.local/bin:$PATH


export PATH="$HOME/miniconda3/bin:$PATH"

if [ -e /etc/profile ]; then
    source /etc/profile
fi

if type ndenv > /dev/null 2>&1; then
    export PATH="$HOME/.ndenv/bin:$PATH"
    eval "$(ndenv init -)"
fi
export PATH="$HOME/google-cloud-sdk/bin:$PATH"
