test -t 0 || exit

bindkey -e

source $HOME/.zplug/init.zsh

zplug "zsh-users/zsh-syntax-highlighting", defer:2
zplug "zsh-users/zsh-completions"
zplug "zsh-users/zsh-autosuggestions"
zplug "zsh-users/zsh-history-substring-search"

zplug "peco/peco", as:command, from:gh-r
zplug "motemen/ghq", as:command, from:gh-r
zplug "mollifier/anyframe"

zplug "powerline/powerline", use:"powerline/bindings/zsh/powerline.zsh"

zplug "simonwhitaker/gibo", as:command, use:"gibo"
zplug "simonwhitaker/gibo", use:"gibo-completion.zsh"

zplug "miyagawa/cpanminus", as:command, use:"cpanm"
zplug "skaji/cpm", as:command, use:"cpm"

zplug check || zplug install
zplug load --verbose

# for cdr
autoload -Uz chpwd_recent_dirs cdr add-zsh-hook
add-zsh-hook chpwd chpwd_recent_dirs


# ctrl-b/f で単語単位の前進/後進
bindkey '' backward-word
bindkey '' forward-word

bindkey '' autosuggest-accept

# anyframe setting
bindkey '' anyframe-widget-put-history
bindkey '' anyframe-widget-insert-filename
bindkey '' anyframe-widget-insert-git-branch
bindkey '' anyframe-widget-cd-ghq-repository
bindkey '' anyframe-widget-execute-history
bindkey '' anyframe-widget-checkout-git-branch
alias cdg=anyframe-widget-cd-ghq-repository
alias cdra=anyframe-widget-cdr


export HISTFILE=${HOME}/.zsh_history
export HISTSIZE=1000
export SAVEHIST=500000
setopt hist_ignore_all_dups # 同じコマンドをヒストリに保存しない
setopt hist_reduce_blanks # 無駄なスペースを消してヒストリに保存する
setopt share_history # ヒストリを共有


# tmuxでもssh-agentが継続されるように
agent="$HOME/.ssh/agent"
if [ -S "$SSH_AUTH_SOCK" ]; then
    case $SSH_AUTH_SOCK in
    /tmp/*/agent.[0-9]*)
        ln -snf "$SSH_AUTH_SOCK" $agent && export SSH_AUTH_SOCK=$agent
    esac
elif [ -S $agent ]; then
    export SSH_AUTH_SOCK=$agent
fi

case ${OSTYPE} in
    darwin*)
        source ${ZDOTDIR}/.zshrc.darwin
        ;;
    linux*)
        source ${ZDOTDIR}/.zshrc.linux
        ;;
esac
