name: macos-ci

on: [push]

jobs:
  ansible:

    runs-on: macOS-latest
    timeout-minutes: 15
    
    steps:
    - uses: actions/checkout@v1
    - name: Remove .gitconfig
      run: rm ~/.gitconfig

    - name: Install Homebrew
      run: /usr/bin/ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)"

    - name: Install Ansible
      run: brew install ansible coreutils
    
    - name: Setup tmate session
      uses: mxschmitt/action-tmate@v1
    
    - name: Run setup
      run: timeout 15m ./setup.sh
      env:
        CI: CI
    - name: Rerun setup
      run: timeout 15m ./setup.sh
      env:
        CI: CI
