name: macos-ci

on: [push]

jobs:
  ansible:

    runs-on: macos-latest
    timeout-minutes: 30
    
    steps:
    - uses: actions/checkout@v2
    - name: Remove .gitconfig
      run: rm ~/.gitconfig

    - name: Install Dotbot
      run: brew install dotbot
      
    - name: Run setup
      run: dotbot -c install.conf.yaml
